# Generated by Django 5.2.6 on 2025-09-21 17:35

import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('Codigo', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Talla', models.CharField(max_length=50)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Diseno', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=50)),
                ('Costo', models.DecimalField(decimal_places=2, default=18, max_digits=10)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('S1', models.IntegerField(default=0)),
                ('S2', models.IntegerField(default=0)),
                ('S3', models.IntegerField(default=0)),
                ('Almacen', models.IntegerField(default=0)),
                ('codigo_barras', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('sucursal_origen', models.CharField(choices=[('S1', 'Sucursal 1'), ('S2', 'Sucursal 2'), ('S3', 'Sucursal 3'), ('A', 'Almacén')], max_length=2)),
                ('sucursal_destino', models.CharField(choices=[('S1', 'Sucursal 1'), ('S2', 'Sucursal 2'), ('S3', 'Sucursal 3'), ('A', 'Almacén')], max_length=2)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10)),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspasos_entregados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productos')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspasos_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=inventory.models.generar_numero_venta, max_length=20, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('sucursal', models.CharField(choices=[('S1', 'Sucursal 1'), ('S2', 'Sucursal 2'), ('S3', 'Sucursal 3'), ('A', 'Almacén')], max_length=2)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('visa', 'Visa'), ('mixto', 'Mixto')], max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('visa', 'Visa'), ('mixto', 'Mixto')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inventory.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.ventas')),
            ],
        ),
    ]
