# Generated by Django 5.2.6 on 2025-09-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('ventas_s1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ventas_s2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ventas_s3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ventas_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ganancia_s1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ganancia_s2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ganancia_s3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ganancia_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-anio', '-mes'],
                'unique_together': {('mes', 'anio')},
            },
        ),
    ]
