# Generated by Django 5.2.6 on 2025-09-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_reportemensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_deposito', models.CharField(help_text='Persona a nombre de quien se hace el depósito', max_length=100)),
                ('nombre_empresa', models.CharField(help_text='Nombre del proveedor o empresa', max_length=150)),
                ('rubro', models.CharField(help_text='Qué es lo que vende el proveedor', max_length=150)),
                ('celular', models.CharField(help_text='Número de contacto del proveedor', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
