# Generated by Django 5.2.6 on 2025-09-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('celular', models.CharField(max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
