# Generated by Django 5.2.6 on 2025-09-23 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('cambio', 'Cambio')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='ventas',
            name='venta_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios', to='inventory.ventas'),
        ),
    ]
