# Generated by Django 5.2.6 on 2025-09-23 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_ventas_tipo_ventas_venta_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='venta_origen',
        ),
    ]
