# Generated by Django 5.2.6 on 2025-09-23 22:46

import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_ventas_tipo_remove_ventas_venta_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=inventory.models.generar_numero_cambio, max_length=20, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('sucursal', models.CharField(choices=[('S1', 'Sucursal 1'), ('S2', 'Sucursal 2'), ('S3', 'Sucursal 3'), ('A', 'Almacén')], max_length=2)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_cambio', to='inventory.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleNotaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('tipo', models.CharField(choices=[('devuelto', 'Devuelto'), ('nuevo', 'Nuevo')], max_length=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productos')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.notacambio')),
            ],
        ),
    ]
