# Generated by Django 5.2.6 on 2025-09-23 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_notacambio_detallenotacambio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallenotacambio',
            old_name='nota',
            new_name='nota_cambio',
        ),
        migrations.RemoveField(
            model_name='detallenotacambio',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detallenotacambio',
            name='tipo',
        ),
        migrations.AddField(
            model_name='detallenotacambio',
            name='producto_devuelto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_devueltos', to='inventory.productos'),
        ),
        migrations.AddField(
            model_name='detallenotacambio',
            name='producto_entregado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_entregados', to='inventory.productos'),
        ),
    ]
